# FROM alpine:latest

# RUN apk add openjdk17
# RUN mkdir -p /opt/e-commerce

# RUN wget https://github.com/Kamila-Kapinos/e-commerce/releases/download/v1.11/my-ecommerce-0.1.jar -O /opt/e-commerce/app.jar

# RUN adduser app --disabled-password

# EXPOSE 8080

# USER app
# CMD ["usr/bin/java", "-Dserver.port=8080", "-jar", "/opt/e-commerce/app.jar"]

FROM alpine:3.16

RUN apk add openjdk11
RUN apk add curl

WORKDIR /opt

RUN curl -L -o app.jar https://github.com/jkanclerz/e-commerce-pp4/releases/download/v.0.3/application.jar

RUN adduser app --disabled-password
USER app

ENV ACTIVE_PROFILE=dev
EXPOSE 8080

# CMD ["/usr/bin/java", "-Dspring.profiles.active=${ACTIVE_PROFILE}", "-jar", "app.jar"]
CMD ["usr/bin/java", "-Dserver.port=8080", "-jar", "/opt/e-commerce/app.jar"]